# PATHS
# 1
#IMAGES_PATH = "jian/"
#GREEN_PATH = IMAGES_PATH + "green/"
#PHASE_PATH = IMAGES_PATH + "phase/"
# 2
IMAGES_PATH = "MEF1/"
GREEN_PATH = IMAGES_PATH + "TSV_green/"
PHASE_PATH = IMAGES_PATH + "TSV_phase/"

#GREEN_PATH = IMAGES_PATH + "Masks_phase/"
#PHASE_PATH = IMAGES_PATH + "TSV_Labeled_phase/"